apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: python-todo
  labels: { app: python-todo }
spec:
  
  replicas: 1
  selector:
    matchLabels: { app: python-todo }
  template:
    metadata:
      labels: { app: python-todo }
    spec:
      containers:
        - name: python
          image: swapnilsrd/todo-python:v2
          ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: python-todo
  namespace: apps
spec:
  
  type: NodePort
  selector:
    app: python-todo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080

